// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhXA-D8oFc3Zp2lJMI0-5X0ajlNHBq8ZA',
    appId: '1:723518225505:web:bc3a510a2a993e2e663e20',
    messagingSenderId: '723518225505',
    projectId: 'amspsingh-notes-project',
    authDomain: 'amspsingh-notes-project.firebaseapp.com',
    storageBucket: 'amspsingh-notes-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FuZ-_GVWRewdbFG6M-E3N6H_gXLhpiM',
    appId: '1:723518225505:android:a79f01d81ea6a6ec663e20',
    messagingSenderId: '723518225505',
    projectId: 'amspsingh-notes-project',
    storageBucket: 'amspsingh-notes-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlsCFHmJyIg7Uj12Vznm7G0aeC9UTZFW4',
    appId: '1:723518225505:ios:7943938e01fb2e18663e20',
    messagingSenderId: '723518225505',
    projectId: 'amspsingh-notes-project',
    storageBucket: 'amspsingh-notes-project.appspot.com',
    iosClientId: '723518225505-g70uu0tb5gevfrs9ng0fnmtg0icv8lh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
